<?php

/**
 * @file
 * Hooks and functions for this module.
 */

/**
 * Implements hook_menu().
 */
function pcdora_menu() {
  $items = array();
  $items['raw/islandora/%islandora_object/%'] = array(
    'title' => 'Raw image callback',
    'page callback' => 'pcdora_raw_image',
    'page arguments' => array(2, 3),
    'access callback' => TRUE,
    'file' => 'includes/callbacks.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function pcdora_theme() {
  return array(
    'pcdora_raw' => array(
      'template' => 'theme/pcdora-raw-image',
      'variables' => array(
        'raw' => NULL,
      ),
    ),
  );
}

/**
 * Implements hook_preprocess().
 */
function pcdora_preprocess_islandora_basic_image(&$variables) {
  $islandora_object = $variables['islandora_object'];
  if (!is_null($islandora_object->id)) {
    $link_url = url("raw/islandora/{$islandora_object->id}/OBJ", array('absolute' => TRUE));
    if (isset($variables['islandora_full_url'])) {
      $variables['islandora_content'] = l($variables['islandora_medium_img'], $link_url, array('html' => TRUE));
    }
    else {
      $variables['islandora_content'] = $variables['islandora_medium_img'];
    }
  }
}
